version: '3'

services:
  thornode_bot_testnet:
    container_name: thornode_bot_testnet

    # comment 'image:' in and 'build:' out to use official image from docker hub
    # comment 'image:' out and 'build:' in to build an image from your local directory
    image: "block42blockchaincompany/thornode_bot:latest"
    #build: .

    env_file:
      - variables-testnet.env
    volumes:
      - thornode-bot-testnet-volume:/storage

  mongodb_container:
    image: mongo:latest
    ports:
      - 42042:27017
    volumes:
      - thornode-bot-mongodb:/data/db

volumes:
  thornode-bot-testnet-volume:
  thornode-bot-mongodb:


# If you have problems running 'docker-compose up' and you're using a VPN, try to run this command in the console:
# docker network create vpnworkaround --subnet 10.0.1.0/24
# ... and uncomment the networks configuration below:
# (solution from https://github.com/docker/for-linux/issues/418#issuecomment-491323611)

#networks:
#  default:
#    external:
#      name: vpnworkaround
