version: '3'

services:
  tendermint_client_container:
    container_name: thornode_tendermint_client
    image: block42blockchaincompany/thorchain-parser:latest
    depends_on:
      - mongodb_container

  mongodb_container:
    container_name: thornode-bot-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - thornode-bot-mongodb:/data/db
      - ./scripts/mongo-setup.sh:/docker-entrypoint-initdb.d/mongo-setup.sh
      - ./snapshot:/snapshot/

volumes:
  thornode-bot-mongodb:

# If you have problems running 'docker-compose up' and you're using a VPN, try to run this command in the console:
# docker network create vpnworkaround --subnet 10.0.1.0/24
# ... and uncomment the networks configuration below:
# (solution from https://github.com/docker/for-linux/issues/418#issuecomment-491323611)

#networks:
#  default:
#    external:
#      name: vpnworkaround