version: '3'

services:
  thornode_bot_testnet:
    container_name: thornode_bot_testnet
    image: block42blockchaincompany/thornode_bot:latest
    #build: .
    depends_on:
      - mongodb_container
      - tendermint_client_container
    env_file:
      - variables-testnet.env
    volumes:
      - thornode-bot-testnet-volume:/storage

volumes:
  thornode-bot-testnet-volume:

# If you have problems running 'docker-compose up' and you're using a VPN, try to run this command in the console:
# docker network create vpnworkaround --subnet 10.0.1.0/24
# ... and uncomment the networks configuration below:
# (solution from https://github.com/docker/for-linux/issues/418#issuecomment-491323611)

#networks:
#  default:
#    external:
#      name: vpnworkaround
