apiVersion: apps/v1
kind: Deployment
metadata:
  name: thornode-bot-deployment-chaosnet
  namespace: thornode-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thornode-bot-deployment-chaosnet
  template:
    metadata:
      labels:
        app: thornode-bot-deployment-chaosnet
    spec:
      containers:
        - name: thornode-bot-deployment-chaosnet
          image: block42blockchaincompany/thornode_bot:latest
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: "XXX"                  # Input the API Token you got from @BotFather
            - name: NETWORK_TYPE
              value: "CHAOSNET"             # Choose "CHAOSNET" or "TESTNET"
            - name: ADMIN_USER_IDS
              value: "1234,5678,42"         # Leave these values the same (Admin Area is currently not enabled on K8s)
            - name: BINANCE_NODE_IPS
              value: ""                     # Node IPs of your Binance nodes, "localhost" or leave it empty to not monitor binance node
            - name: ETHEREUM_NODE_IPS
              value: ""                     # Node IPs of your Ethereum nodes, "localhost" or leave it empty to not monitor Ethereum node
            - name: BITCOIN_NODE_IPS
              value: ""                     # Node IPs of your Bitcoin nodes, "localhost" or leave it empty to not monitor Bitcoin node
            - name: BITCOIN_NODE_USERNAMES
              value: ""                     # Comma separated usernames for your bitcoin nodes (for each Bitcoin node ip exactly one username)
            - name: BITCOIN_NODE_PASSWORDS
              value: ""                     # Comma separated passwords for your bitcoin nodes (for each Bitcoin node ip exactly one password)
      volumes:
        - name: thornode-bot-chaosnet-volume
          persistentVolumeClaim:
            claimName: thornode-bot-chaosnet-pvc
