apiVersion: apps/v1
kind: Deployment
metadata:
  name: thornode-bot-deployment-testnet
  namespace: thornode-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thornode-bot-deployment-testnet
  template:
    metadata:
      labels:
        app: thornode-bot-deployment-testnet
    spec:
      containers:
        - name: thornode-bot-deployment-testnet
          image: block42blockchaincompany/thornode_bot:latest
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: "XXX"                  # Input the API Token you got from @BotFather
            - name: NETWORK_TYPE
              value: "TESTNET"              # Choose "CHAOSNET" or "TESTNET"
            - name: BINANCE_NODE_IPS
              value: ""                     # Node IP of your Binance node, "localhost" or leave it empty to not monitor binance node
            - name: ADMIN_USER_IDS
              value: "1234,5678,42"         # Leave these values the same (Admin Area is currently not enabled on K8s)
      volumes:
        - name: thornode-bot-testnet-volume
          persistentVolumeClaim:
            claimName: thornode-bot-testnet-pvc
