apiVersion: apps/v1
kind: Deployment
metadata:
  name: thornode-bot-deployment-testnet
  namespace: thornode-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thornode-bot-deployment-testnet
  template:
    metadata:
      labels:
        app: thornode-bot-deployment-testnet
    spec:
      containers:
        - name: thornode-bot-deployment-testnet
          image: block42blockchaincompany/thornode_bot:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: thornode-bot-chaosnet-volume
              mountPath: /storage
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: "XXX"                  # Input the API Token you got from @BotFather
            - name: NETWORK_TYPE
              value: "TESTNET"              # Choose "CHAOSNET" or "TESTNET"
            - name: ALLOWED_USER_IDS
              value: "ALL"
            - name: BINANCE_NODE_IPS
              value: ""                     # Node IPs of your Binance nodes, "localhost" or leave it empty to not monitor binance node
            - name: ETHEREUM_NODE_IPS
              value: ""                     # Node IPs of your Ethereum nodes, "localhost" or leave it empty to not monitor Ethereum node
            - name: BITCOIN_NODE_IPS
              value: ""                     # Addresses of your Bitcoin nodes, use format `username:password@ip:port'

      volumes:
        - name: thornode-bot-testnet-volume
          persistentVolumeClaim:
            claimName: thornode-bot-testnet-pvc
