apiVersion: v1
kind: Namespace
metadata:
  name: thornode-bot

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thornode-bot-testnet-pvc
  namespace: thornode-bot
  labels:
    pvclaim: thornode-bot-testnet-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thornode-bot-mongodb-testnet-pvc
  namespace: thornode-bot
  labels:
    pvclaim: thornode-bot-mongodb-testnet-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: thornode-bot-mongodb-setup-script
  namespace: thornode-bot
data:
  script.sh: |
    echo "Initialize Database"
    mongorestore /snapshot
    echo "Loaded db from snapshot"
