apiVersion: apps/v1
kind: Deployment
metadata:
  name: thornode-bot-deployment-chaosnet
  namespace: thornode-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thornode-bot-deployment-chaosnet
  template:
    metadata:
      labels:
        app: thornode-bot-deployment-chaosnet
    spec:
      containers:
        - name: thornode-bot-deployment-chaosnet
          image: block42blockchaincompany/thornode_bot:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: thornode-bot-chaosnet-volume
              mountPath: /storage
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: "XXX"                # Input the API Token you got from @BotFather
            - name: NETWORK_TYPE
              value: "CHAOSNET"           # Choose "CHAOSNET" or "TESTNET"
            - name: ALLOWED_USER_IDS
              value: "ALL"                # Leave these values the same (Admin Area is currently not enabled on K8s)
            - name: BINANCE_NODE_IPS
              value: "localhost,0.0.0.0"# Node IPs of your Binance nodes, leave it empty to not monitor binance node
            - name: ETHEREUM_NODE_IPS
              value: ""                 # Node IPs of your Ethereum nodes, leave it empty to not monitor Ethereum node
            - name: BITCOIN_NODE_IPS
              value: ""                 # Addresses of your Bitcoin nodes, use format `username:password@ip:port'

      volumes:
        - name: thornode-bot-chaosnet-volume
          persistentVolumeClaim:
            claimName: thornode-bot-chaosnet-pvc
