apiVersion: apps/v1
kind: Deployment
metadata:
  name: thornode-bot-deployment-testnet
  namespace: thornode-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thornode-bot-deployment-testnet
  template:
    metadata:
      labels:
        app: thornode-bot-deployment-testnet
    spec:
      containers:
        - name: thornode-bot-mongodb # MongoDB
          image: mongo:latest
          volumeMounts:
            - name: thornode-bot-mongodb-testnet-volume
              mountPath: /data/db

            - name: mongodb-setup-script
              mountPath: /docker-entrypoint-initdb.d/mongo-setup.sh
              subPath: script.sh

            - name: mongo-config-snapshot
              mountPath: /snapshot/thorchain/config.bson
              subPath: config.bson

            - name: mongo-churns-snapshot
              mountPath: /snapshot/thorchain/churns.bson
              subPath: churns.bson

        - name: thornode-bot-deployment-testnet
          image: block42blockchaincompany/thornode_bot:latest
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: "XXX"                  # Input the API Token you got from @BotFather
            - name: NETWORK_TYPE
              value: "TESTNET"              # Choose "CHAOSNET" or "TESTNET"
            - name: ALLOWED_USER_IDS
              value: "1234,5678,42"         # Leave these values the same (Admin Area is currently not enabled on K8s)
            - name: BINANCE_NODE_IPS
              value: ""                     # Node IPs of your Binance nodes, "localhost" or leave it empty to not monitor binance node
            - name: ETHEREUM_NODE_IPS
              value: ""                     # Node IPs of your Ethereum nodes, "localhost" or leave it empty to not monitor Ethereum node
            - name: BITCOIN_NODE_IPS
              value: ""                     # Addresses of your Bitcoin nodes, use format `username:password@ip:port'


        - name: thornode-bot-tendermint-client # Tendermint Client
          image: block42blockchaincompany/thorchain-parser:latest
          imagePullPolicy: Always
          env:
            - name: NATIVE_DEPLOYMENT
              value: "True"             # Running in the same pod is the same as running on the same machine

      volumes:
        - name: thornode-bot-testnet-volume
          persistentVolumeClaim:
            claimName: thornode-bot-testnet-pvc

        - name: thornode-bot-mongodb-testnet-volume
          persistentVolumeClaim:
            claimName: thornode-bot-mongodb-testnet-pvc

        - name: mongodb-setup-script
          configMap:
            name: thornode-bot-mongodb-setup-script

        - name: mongo-config-snapshot
          configMap:
            name: thornode-mongo-config-snapshot

        - name: mongo-churns-snapshot
          configMap:
            name: thornode-mongo-churns-snapshot


