apiVersion: v1
kind: Namespace
metadata:
  name: thornode-bot

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thornode-bot-chaosnet-pvc
  namespace: thornode-bot
  labels:
    pvclaim: thornode-bot-chaosnet-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

