name: Run Unit Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Setup python path
        run: export PYTHONPATH="$(pwd)/bot:$(pwd)/test/unit_tests"

      - name: Run tests with pytest
        run: pytest